### PR TITLE
Add linux_aarch64 build

### PR DESCRIPTION
**Pull request by chrisjsewell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

required for https://github.com/conda-forge/qe-feedstock/pull/34

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@conda-forge-admin, please rerender

**Comment by chrisjsewell** [comment]
@jan-janssen this is ready for review

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
@chrisjsewell Feel free to add yourself as maintainer if you are interested.

**Pull request merged**
